### ISSUE TITLE
Gene signatures failed to plot in hiplot and RStudio (ref. last version of UCSCXenaShiny v1.1.12 based on UCSCXenaTools v1.4.8)

### ISSUE THREAD

**Issue by quiquemedina** [openbiox/UCSCXenaShiny#276]
Dear UCSCXenashiny developers,

Today I installed the last version (UCSCXenaShiny v1.1.12 based on UCSCXenaTools v1.4.8) and noticed that queries with gene signatures are failing in the QuickPanCan Analysis.

For example, TCGA: Association Between Molecular Profile and MSI/Stemness/MSI (Radar Show).

Examples of gene signatures that failed plotting in hiplot or RStudio version UCSCXenaShiny v1.1.12 based on UCSCXenaTools v1.4.8
1.	(ADAMTS15 + ADGRG2 + GABRA3 + IGFBPL1 + ROBO2 + SIX3)
2.	(`MT-ATP8` + `MT-ATP6` + `MT-CO1` + `MT-CO2` + `MT-CO3` + `MT-CYB` + `MT-ND1` + `MT-ND2` + `MT-ND3` + `MT-ND4L` + `MT-ND4` + `MT-ND5` + `MT-ND6`)
3. 
**Note**: Those same signatures run perfectly in UCSCXenaShiny v1.1.10 based on UCSCXenaTools v1.4.8

Please see attached figures

Could you please check from your end and if reproducible, reactivate the functionality.

Regards,

[Gene signatures failed to plot in hiplot and RStudio.pdf](https://github.com/openbiox/UCSCXenaShiny/files/13320042/Gene.signatures.failed.to.plot.in.hiplot.and.RStudio.pdf)
Enrique

**Comment by lishensuo** [comment]
#277 Thank you for pointing the bug. I have checked it and changed the corresponding code that will work correctly.

**Comment by quiquemedina** [comment]
@lishensuo, I reinstalled the app via remotes::install_github("openbiox/UCSCXenaShiny") and the problem (not plotting gene signatures) still remains at my end.

Please advise.

**Comment by lishensuo** [comment]
Because the request has not been allowed to merge. Please wait for ShiXiang.



---- Replied Message ----
| From | Enrique Medina ***@***.***> |
| Date | 11/11/2023 00:12 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [openbiox/UCSCXenaShiny] Gene signatures failed to plot in hiplot and RStudio (ref. last version of UCSCXenaShiny v1.1.12 based on UCSCXenaTools v1.4.8) (Issue #276) |

@lishensuo, I reinstalled the app via remotes::install_github("openbiox/UCSCXenaShiny") and the problem (not plotting gene signatures) still remains at my end.

Please advise.

**Comment by ShixiangWang** [comment]
Hi, I have merged the PR. Thanks to shensuo and questions from @quiquemedina

**Comment by quiquemedina** [comment]
Signatures now run perfectly.  Thank you
